package GUI.Util;

public enum Pantalla {
    ABM_CLIENTE,
    CREAR_CLIENTE,
    AM_INMUEBLE,
    MIS_INMUEBLES,
    C_INMUEBLE,
    MENU_PRINCIPAL,
    CREAR_PROPIETARIO,
    ABM_PROPIETARIO,
    GENERAR_RESERVA,
    CATALOGO,
    VER_INMUEBLE,
    LOGIN
}